export interface RegisterDef {
  address: number;
  type: 'input' | 'holding';
  description?: string;
  unit?: string;
  slave: number;
  gain?: number;      // divisor to get real value (10, 100, 1000, etc.)
  count?: number;     // register count: 1=16-bit, 2=32-bit, 4=64-bit
  dataType?: string;  // 'U16' | 'S16' | 'U32' | 'S32' | 'U64' | 'STRING'
}

export const REGISTERS: Record<string, RegisterDef> = {
  // ==========================================================================
  // PLANT INPUT REGISTERS (slave 247, addresses 30001-39999)
  // ==========================================================================

  // EMS & grid status
  EMS_MODE: {
    address: 30003,
    type: 'input',
    description: 'EMS operating mode',
    slave: 247,
    dataType: 'U16',
  },
  GRID_STATUS: {
    address: 30004,
    type: 'input',
    description: 'Grid sensor status (0=Offline, 1=Online)',
    slave: 247,
    dataType: 'U16',
  },
  PLANT_SYSTEM_TIME: {
    address: 30000,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 1,
    slave: 247,
    description: 'System time (epoch seconds)',
  },
  PLANT_SYSTEM_TIMEZONE: {
    address: 30002,
    type: 'input',
    dataType: 'S16',
    gain: 1,
    slave: 247,
    description: 'System timezone offset (minutes)',
  },
  PLANT_GRID_ACTIVE_POWER: {
    address: 30005,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
    description: 'Grid sensor active power (>0 buy, <0 sell)',
  },
  PLANT_GRID_REACTIVE_POWER: {
    address: 30007,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 247,
    unit: 'kvar',
    description: 'Grid sensor reactive power',
  },
  PLANT_ON_OFF_GRID_STATUS: {
    address: 30009,
    type: 'input',
    dataType: 'U16',
    slave: 247,
    description: 'On/Off grid status (0=on, 1=off(auto), 2=off(manual))',
  },
  PLANT_MAX_ACTIVE_POWER: {
    address: 30010,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
    description: 'Max active power',
  },
  PLANT_MAX_APPARENT_POWER: {
    address: 30012,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 1000,
    slave: 247,
    unit: 'kVA',
    description: 'Max apparent power',
  },

  // Battery
  BATTERY_SOC: {
    address: 30014,
    type: 'input',
    description: 'Battery state of charge',
    unit: '%',
    slave: 247,
    gain: 10,
    dataType: 'U16',
  },
  BATTERY_SOH: {
    address: 30087,
    type: 'input',
    description: 'Battery state of health',
    unit: '%',
    slave: 247,
    gain: 10,
    dataType: 'U16',
  },

  // Phase power
  PLANT_PHASE_A_ACTIVE_POWER: {
    address: 30015,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
  },
  PLANT_PHASE_B_ACTIVE_POWER: {
    address: 30017,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
  },
  PLANT_PHASE_C_ACTIVE_POWER: {
    address: 30019,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
  },
  PLANT_PHASE_A_REACTIVE_POWER: {
    address: 30021,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 247,
    unit: 'kvar',
  },
  PLANT_PHASE_B_REACTIVE_POWER: {
    address: 30023,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 247,
    unit: 'kvar',
  },
  PLANT_PHASE_C_REACTIVE_POWER: {
    address: 30025,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 247,
    unit: 'kvar',
  },

  // Alarms (plant merged)
  PLANT_ALARM1: {
    address: 30027,
    type: 'input',
    dataType: 'U16',
    slave: 247,
    description: 'Merged Alarm1 (PCS alarm codes)',
  },
  PLANT_ALARM2: {
    address: 30028,
    type: 'input',
    dataType: 'U16',
    slave: 247,
    description: 'Merged Alarm2 (PCS alarm codes 2)',
  },
  PLANT_ALARM3: {
    address: 30029,
    type: 'input',
    dataType: 'U16',
    slave: 247,
    description: 'Merged Alarm3 (ESS alarm codes)',
  },
  PLANT_ALARM4: {
    address: 30030,
    type: 'input',
    dataType: 'U16',
    slave: 247,
    description: 'Merged Alarm4 (Gateway alarm codes)',
  },
  PLANT_ALARM5: {
    address: 30072,
    type: 'input',
    dataType: 'U16',
    slave: 247,
    description: 'Merged Alarm5 (DC charger alarm codes)',
  },
  PLANT_ALARM6: {
    address: 30280,
    type: 'input',
    dataType: 'U16',
    slave: 247,
    description: 'Merged Alarm6 (Plant alarm 1 - Appendix 12)',
  },
  PLANT_ALARM7: {
    address: 30281,
    type: 'input',
    dataType: 'U16',
    slave: 247,
    description: 'Merged Alarm7 (Plant alarm 2 - Appendix 13)',
  },

  // Plant power
  PLANT_ACTIVE_POWER: {
    address: 30031,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
    description: 'Plant total active power',
  },
  PLANT_REACTIVE_POWER: {
    address: 30033,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 247,
    unit: 'kvar',
  },
  PLANT_PV_POWER: {
    address: 30035,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
    description: 'PV generation power',
  },
  PLANT_ESS_POWER: {
    address: 30037,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
    description: 'ESS power (<0 discharge, >0 charge)',
  },

  // Available power limits
  PLANT_AVAILABLE_MAX_ACTIVE_POWER: {
    address: 30039,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
  },
  PLANT_AVAILABLE_MIN_ACTIVE_POWER: {
    address: 30041,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
  },
  PLANT_AVAILABLE_MAX_REACTIVE_POWER: {
    address: 30043,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 1000,
    slave: 247,
    unit: 'kvar',
  },
  PLANT_AVAILABLE_MIN_REACTIVE_POWER: {
    address: 30045,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 1000,
    slave: 247,
    unit: 'kvar',
  },
  PLANT_ESS_AVAILABLE_MAX_CHARGE_POWER: {
    address: 30047,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
  },
  PLANT_ESS_AVAILABLE_MAX_DISCHARGE_POWER: {
    address: 30049,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
  },

  // Plant running state
  PLANT_RUNNING_STATE: {
    address: 30051,
    type: 'input',
    description: 'Plant running state',
    slave: 247,
    dataType: 'U16',
  },

  // Grid sensor per-phase power
  PLANT_GRID_SENSOR_PHASE_A_ACTIVE_POWER: {
    address: 30052,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
  },
  PLANT_GRID_SENSOR_PHASE_B_ACTIVE_POWER: {
    address: 30054,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
  },
  PLANT_GRID_SENSOR_PHASE_C_ACTIVE_POWER: {
    address: 30056,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
  },
  PLANT_GRID_SENSOR_PHASE_A_REACTIVE_POWER: {
    address: 30058,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 247,
    unit: 'kvar',
  },
  PLANT_GRID_SENSOR_PHASE_B_REACTIVE_POWER: {
    address: 30060,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 247,
    unit: 'kvar',
  },
  PLANT_GRID_SENSOR_PHASE_C_REACTIVE_POWER: {
    address: 30062,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 247,
    unit: 'kvar',
  },

  // ESS capacity
  PLANT_ESS_AVAILABLE_MAX_CHARGE_CAPACITY: {
    address: 30064,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 100,
    slave: 247,
    unit: 'kWh',
  },
  PLANT_ESS_AVAILABLE_MAX_DISCHARGE_CAPACITY: {
    address: 30066,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 100,
    slave: 247,
    unit: 'kWh',
  },
  PLANT_ESS_RATED_CHARGE_POWER: {
    address: 30068,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
  },
  PLANT_ESS_RATED_DISCHARGE_POWER: {
    address: 30070,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
  },
  PLANT_ESS_RATED_ENERGY_CAPACITY: {
    address: 30083,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 100,
    slave: 247,
    unit: 'kWh',
  },
  PLANT_ESS_CHARGE_CUTOFF_SOC: {
    address: 30085,
    type: 'input',
    dataType: 'U16',
    gain: 10,
    slave: 247,
    unit: '%',
  },
  PLANT_ESS_DISCHARGE_CUTOFF_SOC: {
    address: 30086,
    type: 'input',
    dataType: 'U16',
    gain: 10,
    slave: 247,
    unit: '%',
  },

  // V2.7+ accumulated energy registers
  PLANT_ACCUMULATED_PV_ENERGY: {
    address: 30088,
    count: 4,
    type: 'input',
    dataType: 'U64',
    gain: 100,
    slave: 247,
    unit: 'kWh',
    description: 'Total PV generation',
  },
  PLANT_DAILY_CONSUMED_ENERGY: {
    address: 30092,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 100,
    slave: 247,
    unit: 'kWh',
    description: 'Total load daily consumption',
  },
  PLANT_ACCUMULATED_CONSUMED_ENERGY: {
    address: 30094,
    count: 4,
    type: 'input',
    dataType: 'U64',
    gain: 100,
    slave: 247,
    unit: 'kWh',
    description: 'Total load consumption',
  },

  // Smart load total consumption (24 loads, 30098-30145)
  PLANT_SMART_LOAD_1_TOTAL_CONSUMPTION: { address: 30098, count: 2, type: 'input', dataType: 'U32', gain: 100, slave: 247, unit: 'kWh' },
  PLANT_SMART_LOAD_2_TOTAL_CONSUMPTION: { address: 30100, count: 2, type: 'input', dataType: 'U32', gain: 100, slave: 247, unit: 'kWh' },
  PLANT_SMART_LOAD_3_TOTAL_CONSUMPTION: { address: 30102, count: 2, type: 'input', dataType: 'U32', gain: 100, slave: 247, unit: 'kWh' },
  PLANT_SMART_LOAD_4_TOTAL_CONSUMPTION: { address: 30104, count: 2, type: 'input', dataType: 'U32', gain: 100, slave: 247, unit: 'kWh' },
  PLANT_SMART_LOAD_5_TOTAL_CONSUMPTION: { address: 30106, count: 2, type: 'input', dataType: 'U32', gain: 100, slave: 247, unit: 'kWh' },
  PLANT_SMART_LOAD_6_TOTAL_CONSUMPTION: { address: 30108, count: 2, type: 'input', dataType: 'U32', gain: 100, slave: 247, unit: 'kWh' },
  PLANT_SMART_LOAD_7_TOTAL_CONSUMPTION: { address: 30110, count: 2, type: 'input', dataType: 'U32', gain: 100, slave: 247, unit: 'kWh' },
  PLANT_SMART_LOAD_8_TOTAL_CONSUMPTION: { address: 30112, count: 2, type: 'input', dataType: 'U32', gain: 100, slave: 247, unit: 'kWh' },
  PLANT_SMART_LOAD_9_TOTAL_CONSUMPTION: { address: 30114, count: 2, type: 'input', dataType: 'U32', gain: 100, slave: 247, unit: 'kWh' },
  PLANT_SMART_LOAD_10_TOTAL_CONSUMPTION: { address: 30116, count: 2, type: 'input', dataType: 'U32', gain: 100, slave: 247, unit: 'kWh' },
  PLANT_SMART_LOAD_11_TOTAL_CONSUMPTION: { address: 30118, count: 2, type: 'input', dataType: 'U32', gain: 100, slave: 247, unit: 'kWh' },
  PLANT_SMART_LOAD_12_TOTAL_CONSUMPTION: { address: 30120, count: 2, type: 'input', dataType: 'U32', gain: 100, slave: 247, unit: 'kWh' },
  PLANT_SMART_LOAD_13_TOTAL_CONSUMPTION: { address: 30122, count: 2, type: 'input', dataType: 'U32', gain: 100, slave: 247, unit: 'kWh' },
  PLANT_SMART_LOAD_14_TOTAL_CONSUMPTION: { address: 30124, count: 2, type: 'input', dataType: 'U32', gain: 100, slave: 247, unit: 'kWh' },
  PLANT_SMART_LOAD_15_TOTAL_CONSUMPTION: { address: 30126, count: 2, type: 'input', dataType: 'U32', gain: 100, slave: 247, unit: 'kWh' },
  PLANT_SMART_LOAD_16_TOTAL_CONSUMPTION: { address: 30128, count: 2, type: 'input', dataType: 'U32', gain: 100, slave: 247, unit: 'kWh' },
  PLANT_SMART_LOAD_17_TOTAL_CONSUMPTION: { address: 30130, count: 2, type: 'input', dataType: 'U32', gain: 100, slave: 247, unit: 'kWh' },
  PLANT_SMART_LOAD_18_TOTAL_CONSUMPTION: { address: 30132, count: 2, type: 'input', dataType: 'U32', gain: 100, slave: 247, unit: 'kWh' },
  PLANT_SMART_LOAD_19_TOTAL_CONSUMPTION: { address: 30134, count: 2, type: 'input', dataType: 'U32', gain: 100, slave: 247, unit: 'kWh' },
  PLANT_SMART_LOAD_20_TOTAL_CONSUMPTION: { address: 30136, count: 2, type: 'input', dataType: 'U32', gain: 100, slave: 247, unit: 'kWh' },
  PLANT_SMART_LOAD_21_TOTAL_CONSUMPTION: { address: 30138, count: 2, type: 'input', dataType: 'U32', gain: 100, slave: 247, unit: 'kWh' },
  PLANT_SMART_LOAD_22_TOTAL_CONSUMPTION: { address: 30140, count: 2, type: 'input', dataType: 'U32', gain: 100, slave: 247, unit: 'kWh' },
  PLANT_SMART_LOAD_23_TOTAL_CONSUMPTION: { address: 30142, count: 2, type: 'input', dataType: 'U32', gain: 100, slave: 247, unit: 'kWh' },
  PLANT_SMART_LOAD_24_TOTAL_CONSUMPTION: { address: 30144, count: 2, type: 'input', dataType: 'U32', gain: 100, slave: 247, unit: 'kWh' },

  // Smart load power (24 loads, 30146-30193)
  PLANT_SMART_LOAD_1_POWER: { address: 30146, count: 2, type: 'input', dataType: 'S32', gain: 1000, slave: 247, unit: 'kW' },
  PLANT_SMART_LOAD_2_POWER: { address: 30148, count: 2, type: 'input', dataType: 'S32', gain: 1000, slave: 247, unit: 'kW' },
  PLANT_SMART_LOAD_3_POWER: { address: 30150, count: 2, type: 'input', dataType: 'S32', gain: 1000, slave: 247, unit: 'kW' },
  PLANT_SMART_LOAD_4_POWER: { address: 30152, count: 2, type: 'input', dataType: 'S32', gain: 1000, slave: 247, unit: 'kW' },
  PLANT_SMART_LOAD_5_POWER: { address: 30154, count: 2, type: 'input', dataType: 'S32', gain: 1000, slave: 247, unit: 'kW' },
  PLANT_SMART_LOAD_6_POWER: { address: 30156, count: 2, type: 'input', dataType: 'S32', gain: 1000, slave: 247, unit: 'kW' },
  PLANT_SMART_LOAD_7_POWER: { address: 30158, count: 2, type: 'input', dataType: 'S32', gain: 1000, slave: 247, unit: 'kW' },
  PLANT_SMART_LOAD_8_POWER: { address: 30160, count: 2, type: 'input', dataType: 'S32', gain: 1000, slave: 247, unit: 'kW' },
  PLANT_SMART_LOAD_9_POWER: { address: 30162, count: 2, type: 'input', dataType: 'S32', gain: 1000, slave: 247, unit: 'kW' },
  PLANT_SMART_LOAD_10_POWER: { address: 30164, count: 2, type: 'input', dataType: 'S32', gain: 1000, slave: 247, unit: 'kW' },
  PLANT_SMART_LOAD_11_POWER: { address: 30166, count: 2, type: 'input', dataType: 'S32', gain: 1000, slave: 247, unit: 'kW' },
  PLANT_SMART_LOAD_12_POWER: { address: 30168, count: 2, type: 'input', dataType: 'S32', gain: 1000, slave: 247, unit: 'kW' },
  PLANT_SMART_LOAD_13_POWER: { address: 30170, count: 2, type: 'input', dataType: 'S32', gain: 1000, slave: 247, unit: 'kW' },
  PLANT_SMART_LOAD_14_POWER: { address: 30172, count: 2, type: 'input', dataType: 'S32', gain: 1000, slave: 247, unit: 'kW' },
  PLANT_SMART_LOAD_15_POWER: { address: 30174, count: 2, type: 'input', dataType: 'S32', gain: 1000, slave: 247, unit: 'kW' },
  PLANT_SMART_LOAD_16_POWER: { address: 30176, count: 2, type: 'input', dataType: 'S32', gain: 1000, slave: 247, unit: 'kW' },
  PLANT_SMART_LOAD_17_POWER: { address: 30178, count: 2, type: 'input', dataType: 'S32', gain: 1000, slave: 247, unit: 'kW' },
  PLANT_SMART_LOAD_18_POWER: { address: 30180, count: 2, type: 'input', dataType: 'S32', gain: 1000, slave: 247, unit: 'kW' },
  PLANT_SMART_LOAD_19_POWER: { address: 30182, count: 2, type: 'input', dataType: 'S32', gain: 1000, slave: 247, unit: 'kW' },
  PLANT_SMART_LOAD_20_POWER: { address: 30184, count: 2, type: 'input', dataType: 'S32', gain: 1000, slave: 247, unit: 'kW' },
  PLANT_SMART_LOAD_21_POWER: { address: 30186, count: 2, type: 'input', dataType: 'S32', gain: 1000, slave: 247, unit: 'kW' },
  PLANT_SMART_LOAD_22_POWER: { address: 30188, count: 2, type: 'input', dataType: 'S32', gain: 1000, slave: 247, unit: 'kW' },
  PLANT_SMART_LOAD_23_POWER: { address: 30190, count: 2, type: 'input', dataType: 'S32', gain: 1000, slave: 247, unit: 'kW' },
  PLANT_SMART_LOAD_24_POWER: { address: 30192, count: 2, type: 'input', dataType: 'S32', gain: 1000, slave: 247, unit: 'kW' },

  // Third party PV
  PLANT_THIRD_PARTY_PV_POWER: {
    address: 30194,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
  },
  PLANT_THIRD_PARTY_PV_TOTAL_ENERGY: {
    address: 30196,
    count: 4,
    type: 'input',
    dataType: 'U64',
    gain: 100,
    slave: 247,
    unit: 'kWh',
  },

  // V2.7+ accumulated energy by source (U64 = 4 registers each)
  PLANT_ACCUMULATED_BATTERY_CHARGE_ENERGY: {
    address: 30200,
    count: 4,
    type: 'input',
    dataType: 'U64',
    gain: 100,
    slave: 247,
    unit: 'kWh',
  },
  PLANT_ACCUMULATED_BATTERY_DISCHARGE_ENERGY: {
    address: 30204,
    count: 4,
    type: 'input',
    dataType: 'U64',
    gain: 100,
    slave: 247,
    unit: 'kWh',
  },
  PLANT_EVDC_CHARGE_ENERGY: {
    address: 30208,
    count: 4,
    type: 'input',
    dataType: 'U64',
    gain: 100,
    slave: 247,
    unit: 'kWh',
  },
  PLANT_EVDC_DISCHARGE_ENERGY: {
    address: 30212,
    count: 4,
    type: 'input',
    dataType: 'U64',
    gain: 100,
    slave: 247,
    unit: 'kWh',
  },
  PLANT_GRID_IMPORT_ENERGY: {
    address: 30216,
    count: 4,
    type: 'input',
    dataType: 'U64',
    gain: 100,
    slave: 247,
    unit: 'kWh',
  },
  PLANT_GRID_EXPORT_ENERGY: {
    address: 30220,
    count: 4,
    type: 'input',
    dataType: 'U64',
    gain: 100,
    slave: 247,
    unit: 'kWh',
  },
  PLANT_GENERATOR_ENERGY: {
    address: 30224,
    count: 4,
    type: 'input',
    dataType: 'U64',
    gain: 100,
    slave: 247,
    unit: 'kWh',
  },
  PLANT_COMMON_LOADS_ENERGY: {
    address: 30228,
    count: 4,
    type: 'input',
    dataType: 'U64',
    gain: 100,
    slave: 247,
    unit: 'kWh',
  },
  PLANT_EVAC_CHARGE_ENERGY: {
    address: 30232,
    count: 4,
    type: 'input',
    dataType: 'U64',
    gain: 100,
    slave: 247,
    unit: 'kWh',
  },
  PLANT_SELF_PV_TOTAL_ENERGY: {
    address: 30236,
    count: 4,
    type: 'input',
    dataType: 'U64',
    gain: 100,
    slave: 247,
    unit: 'kWh',
  },

  // V2.8 new registers
  PLANT_GRID_CODE_RATED_FREQUENCY: {
    address: 30276,
    type: 'input',
    dataType: 'U16',
    gain: 100,
    slave: 247,
    unit: 'Hz',
  },
  PLANT_GRID_CODE_RATED_VOLTAGE: {
    address: 30277,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 100,
    slave: 247,
    unit: 'V',
  },
  PLANT_CURRENT_CONTROL_COMMAND: {
    address: 30279,
    type: 'input',
    dataType: 'U16',
    gain: 100,
    slave: 247,
    unit: '%',
  },
  PLANT_GENERAL_LOAD_POWER: {
    address: 30282,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
  },
  PLANT_TOTAL_LOAD_POWER: {
    address: 30284,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
  },

  // ==========================================================================
  // PLANT HOLDING REGISTERS (slave 247, addresses 40001-49999)
  // ==========================================================================

  PLANT_START_STOP: {
    address: 40000,
    type: 'holding',
    dataType: 'U16',
    slave: 247,
    description: 'Plant start/stop (0=stop, 1=start)',
  },
  PLANT_ACTIVE_POWER_ADJUST: {
    address: 40001,
    count: 2,
    type: 'holding',
    dataType: 'S32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
  },
  PLANT_REACTIVE_POWER_ADJUST: {
    address: 40003,
    count: 2,
    type: 'holding',
    dataType: 'S32',
    gain: 1000,
    slave: 247,
    unit: 'kvar',
  },
  PLANT_ACTIVE_POWER_PERCENT: {
    address: 40005,
    type: 'holding',
    dataType: 'S16',
    gain: 100,
    slave: 247,
    unit: '%',
  },
  PLANT_POWER_FACTOR_ADJUST: {
    address: 40007,
    type: 'holding',
    dataType: 'S16',
    gain: 1000,
    slave: 247,
  },
  PLANT_REMOTE_EMS_ENABLE: {
    address: 40029,
    type: 'holding',
    dataType: 'U16',
    slave: 247,
  },
  PLANT_INDEPENDENT_PHASE_ENABLE: {
    address: 40030,
    type: 'holding',
    dataType: 'U16',
    slave: 247,
  },
  EMS_MODE_SETPOINT: {
    address: 40031,
    type: 'holding',
    description: 'EMS mode setpoint (write)',
    slave: 247,
    dataType: 'U16',
  },
  MAX_CHARGE_LIMIT: {
    address: 40032,
    count: 2,
    type: 'holding',
    description: 'Maximum charging power limit',
    unit: 'kW',
    slave: 247,
    dataType: 'U32',
    gain: 1000,
  },
  MAX_DISCHARGE_LIMIT: {
    address: 40034,
    count: 2,
    type: 'holding',
    description: 'Maximum discharging power limit',
    unit: 'kW',
    slave: 247,
    dataType: 'U32',
    gain: 1000,
  },
  PLANT_PV_MAX_POWER_LIMIT: {
    address: 40036,
    count: 2,
    type: 'holding',
    dataType: 'U32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
  },
  PLANT_EXPORT_LIMIT: {
    address: 40038,
    count: 2,
    type: 'holding',
    dataType: 'U32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
  },
  PLANT_IMPORT_LIMIT: {
    address: 40040,
    count: 2,
    type: 'holding',
    dataType: 'U32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
  },
  PLANT_PCS_EXPORT_LIMIT: {
    address: 40042,
    count: 2,
    type: 'holding',
    dataType: 'U32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
  },
  PLANT_PCS_IMPORT_LIMIT: {
    address: 40044,
    count: 2,
    type: 'holding',
    dataType: 'U32',
    gain: 1000,
    slave: 247,
    unit: 'kW',
  },
  PLANT_ESS_BACKUP_SOC: {
    address: 40046,
    type: 'holding',
    dataType: 'U16',
    gain: 10,
    slave: 247,
    unit: '%',
  },
  PLANT_ESS_CHARGE_CUTOFF_SOC_SET: {
    address: 40047,
    type: 'holding',
    dataType: 'U16',
    gain: 10,
    slave: 247,
    unit: '%',
  },
  PLANT_ESS_DISCHARGE_CUTOFF_SOC_SET: {
    address: 40048,
    type: 'holding',
    dataType: 'U16',
    gain: 10,
    slave: 247,
    unit: '%',
  },
  PLANT_ACTIVE_POWER_GRADIENT: {
    address: 40049,
    count: 2,
    type: 'holding',
    dataType: 'U32',
    gain: 1000,
    slave: 247,
    unit: '%/s',
  },

  // Grid code LVRT/HVRT/OF derating/UF boost registers (40051-40068, V2.8)
  PLANT_LVRT_ENABLE: {
    address: 40051,
    type: 'holding',
    dataType: 'U16',
    slave: 247,
    description: 'LVRT enable',
  },
  PLANT_LVRT_REACTIVE_COMP_FACTOR: {
    address: 40052,
    type: 'holding',
    dataType: 'U16',
    gain: 100,
    slave: 247,
    description: 'LVRT reactive power compensation factor',
  },
  PLANT_LVRT_NEG_SEQ_REACTIVE_FACTOR: {
    address: 40053,
    type: 'holding',
    dataType: 'U16',
    gain: 100,
    slave: 247,
    description: 'LVRT negative-sequence reactive compensation factor',
  },
  PLANT_LVRT_MODE: {
    address: 40054,
    type: 'holding',
    dataType: 'U16',
    slave: 247,
    description: 'LVRT mode',
  },
  PLANT_LVRT_GRID_VOLTAGE_BLOCKING: {
    address: 40055,
    type: 'holding',
    dataType: 'U16',
    slave: 247,
    description: 'LVRT grid voltage protection blocking',
  },
  PLANT_HVRT_ENABLE: {
    address: 40056,
    type: 'holding',
    dataType: 'U16',
    slave: 247,
    description: 'HVRT enable',
  },
  PLANT_HVRT_REACTIVE_COMP_FACTOR: {
    address: 40057,
    type: 'holding',
    dataType: 'U16',
    gain: 100,
    slave: 247,
    description: 'HVRT reactive power compensation factor',
  },
  PLANT_HVRT_NEG_SEQ_REACTIVE_FACTOR: {
    address: 40058,
    type: 'holding',
    dataType: 'U16',
    gain: 100,
    slave: 247,
    description: 'HVRT negative-sequence reactive compensation factor',
  },
  PLANT_HVRT_MODE: {
    address: 40059,
    type: 'holding',
    dataType: 'U16',
    slave: 247,
    description: 'HVRT mode',
  },
  PLANT_HVRT_GRID_VOLTAGE_BLOCKING: {
    address: 40060,
    type: 'holding',
    dataType: 'U16',
    slave: 247,
    description: 'HVRT grid voltage protection blocking',
  },
  PLANT_OF_DERATING_ENABLE: {
    address: 40061,
    type: 'holding',
    dataType: 'U16',
    slave: 247,
    description: 'Over-frequency derating enable',
  },
  PLANT_OF_DERATING_RAMP_RATE: {
    address: 40062,
    type: 'holding',
    dataType: 'U16',
    gain: 100,
    slave: 247,
    unit: '%',
    description: 'Over-frequency derating ramp rate',
  },
  PLANT_OF_DERATING_TRIGGER_FREQ: {
    address: 40063,
    type: 'holding',
    dataType: 'U16',
    gain: 100,
    slave: 247,
    unit: 'Hz',
    description: 'Over-frequency derating trigger frequency',
  },
  PLANT_OF_DERATING_CUTOFF_FREQ: {
    address: 40064,
    type: 'holding',
    dataType: 'U16',
    gain: 100,
    slave: 247,
    unit: 'Hz',
    description: 'Over-frequency derating cut-off frequency',
  },
  PLANT_UF_BOOST_ENABLE: {
    address: 40065,
    type: 'holding',
    dataType: 'U16',
    slave: 247,
    description: 'Under-frequency power boost enable',
  },
  PLANT_UF_BOOST_RAMP_RATE: {
    address: 40066,
    type: 'holding',
    dataType: 'U16',
    gain: 100,
    slave: 247,
    unit: '%',
    description: 'Under-frequency boost ramp rate',
  },
  PLANT_UF_BOOST_TRIGGER_FREQ: {
    address: 40067,
    type: 'holding',
    dataType: 'U16',
    gain: 100,
    slave: 247,
    unit: 'Hz',
    description: 'Under-frequency boost trigger frequency',
  },
  PLANT_UF_BOOST_CUTOFF_FREQ: {
    address: 40068,
    type: 'holding',
    dataType: 'U16',
    gain: 100,
    slave: 247,
    unit: 'Hz',
    description: 'Under-frequency boost cut-off frequency',
  },

  // ==========================================================================
  // INVERTER INPUT REGISTERS (slave 1, addresses 30001-39999)
  // ==========================================================================

  // Inverter info (30500+)
  INVERTER_MODEL_TYPE: {
    address: 30500,
    count: 15,
    type: 'input',
    dataType: 'STRING',
    slave: 1,
    description: 'Model type string',
  },
  INVERTER_SERIAL_NUMBER: {
    address: 30515,
    count: 10,
    type: 'input',
    dataType: 'STRING',
    slave: 1,
  },
  INVERTER_FIRMWARE_VERSION: {
    address: 30525,
    count: 15,
    type: 'input',
    dataType: 'STRING',
    slave: 1,
  },
  INVERTER_RATED_ACTIVE_POWER: {
    address: 30540,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 1000,
    slave: 1,
    unit: 'kW',
  },
  INVERTER_MAX_APPARENT_POWER: {
    address: 30542,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 1000,
    slave: 1,
    unit: 'kVA',
  },
  INVERTER_MAX_ACTIVE_POWER: {
    address: 30544,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 1000,
    slave: 1,
    unit: 'kW',
  },
  INVERTER_MAX_ABSORPTION_POWER: {
    address: 30546,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 1000,
    slave: 1,
    unit: 'kW',
  },
  INVERTER_RATED_BATTERY_CAPACITY: {
    address: 30548,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 100,
    slave: 1,
    unit: 'kWh',
  },
  INVERTER_ESS_RATED_CHARGE_POWER: {
    address: 30550,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 1000,
    slave: 1,
    unit: 'kW',
  },
  INVERTER_ESS_RATED_DISCHARGE_POWER: {
    address: 30552,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 1000,
    slave: 1,
    unit: 'kW',
  },
  INVERTER_ESS_DAILY_CHARGE_ENERGY: {
    address: 30566,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 100,
    slave: 1,
    unit: 'kWh',
  },
  INVERTER_ESS_ACCUMULATED_CHARGE_ENERGY: {
    address: 30568,
    count: 4,
    type: 'input',
    dataType: 'U64',
    gain: 100,
    slave: 1,
    unit: 'kWh',
  },
  INVERTER_ESS_DAILY_DISCHARGE_ENERGY: {
    address: 30572,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 100,
    slave: 1,
    unit: 'kWh',
  },
  INVERTER_ESS_ACCUMULATED_DISCHARGE_ENERGY: {
    address: 30574,
    count: 4,
    type: 'input',
    dataType: 'U64',
    gain: 100,
    slave: 1,
    unit: 'kWh',
  },

  // Inverter running state & battery
  INVERTER_RUNNING_STATE: {
    address: 30578,
    type: 'input',
    description: 'Inverter running state',
    slave: 1,
    dataType: 'U16',
  },
  INVERTER_BATTERY_SOC: {
    address: 30601,
    type: 'input',
    description: 'Inverter battery SOC',
    unit: '%',
    slave: 1,
    gain: 10,
    dataType: 'U16',
  },
  INVERTER_BATTERY_SOH: {
    address: 30602,
    type: 'input',
    description: 'Inverter battery SOH',
    unit: '%',
    slave: 1,
    gain: 10,
    dataType: 'U16',
  },

  // Inverter power limits feedback
  INVERTER_MAX_ACTIVE_ADJUST: {
    address: 30579,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 1,
    unit: 'kW',
  },
  INVERTER_MIN_ACTIVE_ADJUST: {
    address: 30581,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 1,
    unit: 'kW',
  },
  INVERTER_MAX_REACTIVE_ADJUST_FEED: {
    address: 30583,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 1000,
    slave: 1,
    unit: 'kvar',
  },
  INVERTER_MAX_REACTIVE_ADJUST_ABSORB: {
    address: 30585,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 1000,
    slave: 1,
    unit: 'kvar',
  },
  INVERTER_ACTIVE_POWER: {
    address: 30587,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 1,
    unit: 'kW',
  },
  INVERTER_REACTIVE_POWER: {
    address: 30589,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 1,
    unit: 'kvar',
  },
  INVERTER_ESS_MAX_CHARGE_POWER: {
    address: 30591,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 1000,
    slave: 1,
    unit: 'kW',
  },
  INVERTER_ESS_MAX_DISCHARGE_POWER: {
    address: 30593,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 1000,
    slave: 1,
    unit: 'kW',
  },
  INVERTER_ESS_AVAILABLE_CHARGE_ENERGY: {
    address: 30595,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 100,
    slave: 1,
    unit: 'kWh',
  },
  INVERTER_ESS_AVAILABLE_DISCHARGE_ENERGY: {
    address: 30597,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 100,
    slave: 1,
    unit: 'kWh',
  },
  INVERTER_ESS_CHARGE_DISCHARGE_POWER: {
    address: 30599,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 1,
    unit: 'kW',
  },

  // Battery cell temps & voltages
  INVERTER_ESS_AVG_CELL_TEMP: {
    address: 30603,
    type: 'input',
    dataType: 'S16',
    gain: 10,
    slave: 1,
    unit: 'C',
  },
  INVERTER_ESS_AVG_CELL_VOLTAGE: {
    address: 30604,
    type: 'input',
    dataType: 'U16',
    gain: 1000,
    slave: 1,
    unit: 'V',
  },
  INVERTER_ESS_MAX_CELL_TEMP: {
    address: 30620,
    type: 'input',
    dataType: 'S16',
    gain: 10,
    slave: 1,
    unit: 'C',
  },
  INVERTER_ESS_MIN_CELL_TEMP: {
    address: 30621,
    type: 'input',
    dataType: 'S16',
    gain: 10,
    slave: 1,
    unit: 'C',
  },
  INVERTER_ESS_MAX_CELL_VOLTAGE: {
    address: 30622,
    type: 'input',
    dataType: 'U16',
    gain: 1000,
    slave: 1,
    unit: 'V',
  },
  INVERTER_ESS_MIN_CELL_VOLTAGE: {
    address: 30623,
    type: 'input',
    dataType: 'U16',
    gain: 1000,
    slave: 1,
    unit: 'V',
  },

  // Inverter alarm codes
  INVERTER_ALARM1: {
    address: 30605,
    type: 'input',
    dataType: 'U16',
    slave: 1,
    description: 'Inverter Alarm1 (PCS alarm codes)',
  },
  INVERTER_ALARM2: {
    address: 30606,
    type: 'input',
    dataType: 'U16',
    slave: 1,
  },
  INVERTER_ALARM3: {
    address: 30607,
    type: 'input',
    dataType: 'U16',
    slave: 1,
  },
  INVERTER_ALARM4: {
    address: 30608,
    type: 'input',
    dataType: 'U16',
    slave: 1,
  },
  INVERTER_ALARM5: {
    address: 30609,
    type: 'input',
    dataType: 'U16',
    slave: 1,
  },

  // Inverter adjust feedback
  INVERTER_ACTIVE_ADJUST_FEEDBACK: {
    address: 30613,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 1,
    unit: 'kW',
  },
  INVERTER_REACTIVE_ADJUST_FEEDBACK: {
    address: 30615,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 1,
    unit: 'kvar',
  },
  INVERTER_ACTIVE_PERCENT_FEEDBACK: {
    address: 30617,
    type: 'input',
    dataType: 'S16',
    gain: 100,
    slave: 1,
    unit: '%',
  },
  INVERTER_REACTIVE_PERCENT_FEEDBACK: {
    address: 30618,
    type: 'input',
    dataType: 'S16',
    gain: 100,
    slave: 1,
    unit: '%',
  },
  INVERTER_POWER_FACTOR_FEEDBACK: {
    address: 30619,
    type: 'input',
    dataType: 'S16',
    gain: 1000,
    slave: 1,
  },

  // Grid parameters (31000+)
  INVERTER_RATED_GRID_VOLTAGE: {
    address: 31000,
    type: 'input',
    dataType: 'U16',
    gain: 10,
    slave: 1,
    unit: 'V',
  },
  INVERTER_RATED_GRID_FREQUENCY: {
    address: 31001,
    type: 'input',
    dataType: 'U16',
    gain: 100,
    slave: 1,
    unit: 'Hz',
  },
  INVERTER_GRID_FREQUENCY: {
    address: 31002,
    type: 'input',
    dataType: 'U16',
    gain: 100,
    slave: 1,
    unit: 'Hz',
  },
  INVERTER_PCS_INTERNAL_TEMP: {
    address: 31003,
    type: 'input',
    dataType: 'S16',
    gain: 10,
    slave: 1,
    unit: 'C',
  },
  INVERTER_OUTPUT_TYPE: {
    address: 31004,
    type: 'input',
    dataType: 'U16',
    slave: 1,
    description: 'Output type (0=L/N, 1=L1/L2/L3, 2=L1/L2/L3/N, 3=L1/L2/N)',
  },
  INVERTER_AB_LINE_VOLTAGE: {
    address: 31005,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 100,
    slave: 1,
    unit: 'V',
  },
  INVERTER_BC_LINE_VOLTAGE: {
    address: 31007,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 100,
    slave: 1,
    unit: 'V',
  },
  INVERTER_CA_LINE_VOLTAGE: {
    address: 31009,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 100,
    slave: 1,
    unit: 'V',
  },
  INVERTER_PHASE_A_VOLTAGE: {
    address: 31011,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 100,
    slave: 1,
    unit: 'V',
  },
  INVERTER_PHASE_B_VOLTAGE: {
    address: 31013,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 100,
    slave: 1,
    unit: 'V',
  },
  INVERTER_PHASE_C_VOLTAGE: {
    address: 31015,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 100,
    slave: 1,
    unit: 'V',
  },
  INVERTER_PHASE_A_CURRENT: {
    address: 31017,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 100,
    slave: 1,
    unit: 'A',
  },
  INVERTER_PHASE_B_CURRENT: {
    address: 31019,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 100,
    slave: 1,
    unit: 'A',
  },
  INVERTER_PHASE_C_CURRENT: {
    address: 31021,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 100,
    slave: 1,
    unit: 'A',
  },
  INVERTER_POWER_FACTOR: {
    address: 31023,
    type: 'input',
    dataType: 'S16',
    gain: 1000,
    slave: 1,
  },
  INVERTER_PACK_COUNT: {
    address: 31024,
    type: 'input',
    dataType: 'U16',
    slave: 1,
  },
  INVERTER_PV_STRING_COUNT: {
    address: 31025,
    type: 'input',
    dataType: 'U16',
    slave: 1,
  },
  INVERTER_MPPT_COUNT: {
    address: 31026,
    type: 'input',
    dataType: 'U16',
    slave: 1,
  },

  // PV strings 1-4 (existing)
  INVERTER_PV1_VOLTAGE: {
    address: 31027,
    type: 'input',
    description: 'PV string 1 voltage',
    unit: 'V',
    slave: 1,
    gain: 10,
    dataType: 'U16',
  },
  INVERTER_PV1_CURRENT: {
    address: 31028,
    type: 'input',
    description: 'PV string 1 current',
    unit: 'A',
    slave: 1,
    gain: 100,
    dataType: 'S16',
  },
  INVERTER_PV2_VOLTAGE: {
    address: 31029,
    type: 'input',
    description: 'PV string 2 voltage',
    unit: 'V',
    slave: 1,
    gain: 10,
    dataType: 'U16',
  },
  INVERTER_PV2_CURRENT: {
    address: 31030,
    type: 'input',
    description: 'PV string 2 current',
    unit: 'A',
    slave: 1,
    gain: 100,
    dataType: 'S16',
  },
  INVERTER_PV3_VOLTAGE: {
    address: 31031,
    type: 'input',
    description: 'PV string 3 voltage',
    unit: 'V',
    slave: 1,
    gain: 10,
    dataType: 'U16',
  },
  INVERTER_PV3_CURRENT: {
    address: 31032,
    type: 'input',
    description: 'PV string 3 current',
    unit: 'A',
    slave: 1,
    gain: 100,
    dataType: 'S16',
  },
  INVERTER_PV4_VOLTAGE: {
    address: 31033,
    type: 'input',
    description: 'PV string 4 voltage',
    unit: 'V',
    slave: 1,
    gain: 10,
    dataType: 'U16',
  },
  INVERTER_PV4_CURRENT: {
    address: 31034,
    type: 'input',
    description: 'PV string 4 current',
    unit: 'A',
    slave: 1,
    gain: 100,
    dataType: 'S16',
  },

  // PV total power
  INVERTER_PV_POWER: {
    address: 31035,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 1,
    unit: 'kW',
  },
  INVERTER_INSULATION_RESISTANCE: {
    address: 31037,
    type: 'input',
    dataType: 'U16',
    gain: 1000,
    slave: 1,
    unit: 'Mohm',
  },
  INVERTER_STARTUP_TIME: {
    address: 31038,
    count: 2,
    type: 'input',
    dataType: 'U32',
    slave: 1,
    unit: 's',
  },
  INVERTER_SHUTDOWN_TIME: {
    address: 31040,
    count: 2,
    type: 'input',
    dataType: 'U32',
    slave: 1,
    unit: 's',
  },

  // PV strings 5-36 (31042-31105)
  INVERTER_PV5_VOLTAGE: { address: 31042, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV5_CURRENT: { address: 31043, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV6_VOLTAGE: { address: 31044, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV6_CURRENT: { address: 31045, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV7_VOLTAGE: { address: 31046, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV7_CURRENT: { address: 31047, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV8_VOLTAGE: { address: 31048, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV8_CURRENT: { address: 31049, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV9_VOLTAGE: { address: 31050, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV9_CURRENT: { address: 31051, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV10_VOLTAGE: { address: 31052, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV10_CURRENT: { address: 31053, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV11_VOLTAGE: { address: 31054, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV11_CURRENT: { address: 31055, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV12_VOLTAGE: { address: 31056, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV12_CURRENT: { address: 31057, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV13_VOLTAGE: { address: 31058, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV13_CURRENT: { address: 31059, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV14_VOLTAGE: { address: 31060, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV14_CURRENT: { address: 31061, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV15_VOLTAGE: { address: 31062, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV15_CURRENT: { address: 31063, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV16_VOLTAGE: { address: 31064, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV16_CURRENT: { address: 31065, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV17_VOLTAGE: { address: 31066, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV17_CURRENT: { address: 31067, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV18_VOLTAGE: { address: 31068, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV18_CURRENT: { address: 31069, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV19_VOLTAGE: { address: 31070, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV19_CURRENT: { address: 31071, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV20_VOLTAGE: { address: 31072, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV20_CURRENT: { address: 31073, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV21_VOLTAGE: { address: 31074, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV21_CURRENT: { address: 31075, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV22_VOLTAGE: { address: 31076, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV22_CURRENT: { address: 31077, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV23_VOLTAGE: { address: 31078, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV23_CURRENT: { address: 31079, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV24_VOLTAGE: { address: 31080, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV24_CURRENT: { address: 31081, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV25_VOLTAGE: { address: 31082, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV25_CURRENT: { address: 31083, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV26_VOLTAGE: { address: 31084, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV26_CURRENT: { address: 31085, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV27_VOLTAGE: { address: 31086, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV27_CURRENT: { address: 31087, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV28_VOLTAGE: { address: 31088, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV28_CURRENT: { address: 31089, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV29_VOLTAGE: { address: 31090, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV29_CURRENT: { address: 31091, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV30_VOLTAGE: { address: 31092, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV30_CURRENT: { address: 31093, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV31_VOLTAGE: { address: 31094, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV31_CURRENT: { address: 31095, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV32_VOLTAGE: { address: 31096, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV32_CURRENT: { address: 31097, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV33_VOLTAGE: { address: 31098, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV33_CURRENT: { address: 31099, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV34_VOLTAGE: { address: 31100, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV34_CURRENT: { address: 31101, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV35_VOLTAGE: { address: 31102, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV35_CURRENT: { address: 31103, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },
  INVERTER_PV36_VOLTAGE: { address: 31104, type: 'input', dataType: 'S16', gain: 10, slave: 1, unit: 'V' },
  INVERTER_PV36_CURRENT: { address: 31105, type: 'input', dataType: 'S16', gain: 100, slave: 1, unit: 'A' },

  // PV daily/total generation
  INVERTER_PV_DAILY_GENERATION: {
    address: 31509,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 100,
    slave: 1,
    unit: 'kWh',
  },
  INVERTER_PV_TOTAL_GENERATION: {
    address: 31511,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 100,
    slave: 1,
    unit: 'kWh',
  },

  // ==========================================================================
  // DC CHARGER INPUT REGISTERS (slave 1)
  // ==========================================================================

  DC_CHARGER_VOLTAGE: {
    address: 31500,
    type: 'input',
    description: 'DC charger vehicle battery voltage',
    unit: 'V',
    slave: 1,
    gain: 10,
    dataType: 'U16',
  },
  DC_CHARGER_CURRENT: {
    address: 31501,
    type: 'input',
    description: 'DC charger charging current',
    unit: 'A',
    slave: 1,
    gain: 10,
    dataType: 'U16',
  },
  DC_CHARGER_POWER: {
    address: 31502,
    count: 2,
    type: 'input',
    description: 'DC charger output power',
    unit: 'kW',
    slave: 1,
    gain: 1000,
    dataType: 'S32',
  },
  DC_CHARGER_VEHICLE_SOC: {
    address: 31504,
    type: 'input',
    description: 'EV vehicle SOC',
    unit: '%',
    slave: 1,
    gain: 10,
    dataType: 'U16',
  },
  DC_CHARGER_CURRENT_CHARGING_CAPACITY: {
    address: 31505,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 100,
    slave: 1,
    unit: 'kWh',
  },
  DC_CHARGER_CURRENT_CHARGING_DURATION: {
    address: 31507,
    count: 2,
    type: 'input',
    dataType: 'U32',
    slave: 1,
    unit: 's',
  },
  DC_CHARGER_STATUS: {
    address: 31513,
    type: 'input',
    description: 'DC charger operating status',
    slave: 1,
    dataType: 'U16',
  },

  // ==========================================================================
  // AC CHARGER INPUT REGISTERS (slave 1)
  // ==========================================================================

  AC_CHARGER_SYSTEM_STATE: {
    address: 32000,
    type: 'input',
    dataType: 'U16',
    slave: 1,
    description: 'AC charger system state (Appendix 7)',
  },
  AC_CHARGER_TOTAL_ENERGY: {
    address: 32001,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 100,
    slave: 1,
    unit: 'kWh',
  },
  AC_CHARGER_CHARGING_POWER: {
    address: 32003,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 1000,
    slave: 1,
    unit: 'kW',
  },
  AC_CHARGER_RATED_POWER: {
    address: 32005,
    count: 2,
    type: 'input',
    dataType: 'U32',
    gain: 1000,
    slave: 1,
    unit: 'kW',
  },
  AC_CHARGER_RATED_CURRENT: {
    address: 32007,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 100,
    slave: 1,
    unit: 'A',
  },
  AC_CHARGER_RATED_VOLTAGE: {
    address: 32009,
    type: 'input',
    dataType: 'U16',
    gain: 10,
    slave: 1,
    unit: 'V',
  },
  AC_CHARGER_INPUT_BREAKER_CURRENT: {
    address: 32010,
    count: 2,
    type: 'input',
    dataType: 'S32',
    gain: 100,
    slave: 1,
    unit: 'A',
  },
  AC_CHARGER_ALARM1: {
    address: 32012,
    type: 'input',
    dataType: 'U16',
    slave: 1,
    description: 'AC charger Alarm1 (Appendix 8)',
  },
  AC_CHARGER_ALARM2: {
    address: 32013,
    type: 'input',
    dataType: 'U16',
    slave: 1,
    description: 'AC charger Alarm2 (Appendix 9)',
  },
  AC_CHARGER_ALARM3: {
    address: 32014,
    type: 'input',
    dataType: 'U16',
    slave: 1,
    description: 'AC charger Alarm3 (Appendix 10)',
  },

  // ==========================================================================
  // INVERTER HOLDING REGISTERS (slave 1, addresses 40001-49999)
  // ==========================================================================

  INVERTER_START_STOP: {
    address: 40500,
    type: 'holding',
    dataType: 'U16',
    slave: 1,
    description: 'Inverter start/stop (0=stop, 1=start)',
  },
  DC_CHARGER_START_STOP: {
    address: 41000,
    type: 'holding',
    dataType: 'U16',
    slave: 1,
    description: 'DC charger start/stop (0=start, 1=stop)',
  },

  // ==========================================================================
  // AC CHARGER HOLDING REGISTERS (slave 1)
  // ==========================================================================

  AC_CHARGER_START_STOP: {
    address: 42000,
    type: 'holding',
    dataType: 'U16',
    slave: 1,
    description: 'AC charger start/stop (0=start, 1=stop)',
  },
  AC_CHARGER_OUTPUT_CURRENT: {
    address: 42001,
    count: 2,
    type: 'holding',
    dataType: 'U32',
    gain: 100,
    slave: 1,
    unit: 'A',
  },
};

// =============================================================================
// ENUM MAPS (Appendix tables from V2.8 Modbus Protocol)
// =============================================================================

// EMS work mode (register 30003) values per Modbus protocol v2.8
export const EMS_MODES: Record<number, string> = {
  0: 'Maximum Self Consumption',
  1: 'AI Mode',
  2: 'TOU (Time of Use)',
  5: 'Full Feed-In to Grid',
  6: 'VPP Scheduling',
  7: 'Remote EMS',
  9: 'Custom',
};

// Grid connection status (register 30004 / 30009)
export const GRID_STATUSES: Record<number, string> = {
  0: 'On Grid',
  1: 'Off Grid (Auto)',
  2: 'Off Grid (Manual)',
};

// DC charger running state (register 31513, legacy mapping up to V2.7)
export const DC_CHARGER_STATUSES: Record<number, string> = {
  0: 'System Init',
  1: 'Standby (A1/A2)',
  2: 'Pre-charge (B1)',
  3: 'Connection Check (B2)',
  4: 'Charging (C1)',
  5: 'Charging (C2)',
  6: 'Fault (F)',
};

// Plant / Inverter running states
export const RUNNING_STATES: Record<number, string> = {
  0: 'Standby',
  1: 'Running',
  2: 'Fault',
  3: 'Shutdown',
  7: 'Environmental Abnormality',
};

// Remote EMS modes (EMS_MODE = 7 sub-modes)
export const REMOTE_EMS_MODES: Record<number, string> = {
  0: 'PCS Remote Control',
  1: 'Standby',
  2: 'Maximum Self-Consumption',
  3: 'Command Charging (Grid First)',
  4: 'Command Charging (PV First)',
  5: 'Command Discharging (PV First)',
  6: 'Command Discharging (ESS First)',
};

// AC charger system states (Appendix 7)
export const AC_CHARGER_STATES: Record<number, string> = {
  0: 'System Init',
  1: 'A1/A2 (Standby)',
  2: 'B1 (Pre-charge)',
  3: 'B2 (Connection Check)',
  4: 'C1 (Charging)',
  5: 'C2 (Charging)',
  6: 'F (Fault)',
  7: 'E (Error)',
};

// DC charger running state - V2.8 expanded states
export const DC_CHARGER_RUNNING_STATE_V28: Record<number, string> = {
  0x00: 'Idle',
  0x01: 'Occupied',
  0x02: 'Preparing (Comm)',
  0x03: 'Charging',
  0x04: 'Fault',
  0x05: 'Scheduled',
  0x06: 'Ended',
  0x07: 'Unavailable',
  0x08: 'Discharging',
  0x09: 'Alarm',
  0x0A: 'Preparing (Insulation)',
};

// Output types (register 31004)
export const OUTPUT_TYPES: Record<number, string> = {
  0: 'L/N',
  1: 'L1/L2/L3',
  2: 'L1/L2/L3/N',
  3: 'L1/L2/N',
};

// =============================================================================
// ALARM CODE BIT-FIELD MAPS (Appendices from V2.8 spec)
// Each alarm register is a bit field. The maps below decode individual bits.
// =============================================================================

// PCS alarm codes (Appendix 1, Alarm1)
export const PCS_ALARM_CODES: Record<number, string> = {
  0: 'Software version mismatch',
  1: 'Low insulation resistance',
  2: 'Over-temperature',
  3: 'Equipment fault',
  4: 'System grounding fault',
  5: 'PV string over-voltage',
  6: 'PV string reversely connected',
  7: 'PV string back-filling',
  8: 'AFCI fault',
  9: 'Grid power outage',
  10: 'Grid over-voltage',
  11: 'Grid under-voltage',
  12: 'Grid over-frequency',
  13: 'Grid under-frequency',
  14: 'Grid voltage imbalance',
  15: 'DC component out of limit',
};

// PCS alarm codes 2 (Appendix 2, Alarm2)
export const PCS_ALARM_CODES2: Record<number, string> = {
  0: 'Leak current out of limit',
  1: 'Communication abnormal',
  2: 'System internal protection',
  3: 'AFCI self-check circuit fault',
  4: 'Off-grid protection',
  5: 'Manual operation protection',
  7: 'Abnormal phase sequence',
  8: 'Short circuit to PE',
  9: 'Soft start failure',
};

// ESS alarm codes (Appendix 3, Alarm3)
export const ESS_ALARM_CODES: Record<number, string> = {
  0: 'Software version mismatch',
  1: 'Low insulation resistance to ground',
  2: 'Temperature too high',
  3: 'Equipment fault',
  4: 'Under-temperature',
  5: 'Internal protection',
  6: 'Thermal runaway',
};

// Gateway alarm codes (Appendix 4, Alarm4)
export const GATEWAY_ALARM_CODES: Record<number, string> = {
  0: 'Software version mismatch',
  1: 'Temperature too high',
  2: 'Equipment fault',
  3: 'Excessive leakage current in off-grid output',
  4: 'N line grounding fault',
  5: 'Abnormal phase sequence of grid wiring',
  6: 'Abnormal phase sequence of inverter wiring',
  7: 'Grid phase loss',
};

// DC charger alarm codes (Appendix 5, Alarm5)
export const DC_CHARGER_ALARM_CODES: Record<number, string> = {
  0: 'Software version mismatch',
  1: 'Low insulation resistance to ground',
  2: 'Over-temperature',
  3: 'Equipment fault',
  4: 'Charging fault',
  5: 'Equipment protection',
};

// Plant alarm codes 6 (Appendix 12, Alarm6)
export const PLANT_ALARM_CODES6: Record<number, string> = {
  0: 'Gateway communication abnormal',
  1: 'Meter communication abnormal',
  2: 'AC power sensor communication abnormal',
  6: 'Hard protection against grid-feed power limit exceedance',
  8: 'Generator failure to start',
  10: 'CLS fault',
};

// Plant alarm codes 7 (Appendix 13, Alarm7)
export const PLANT_ALARM_CODES7: Record<number, string> = {
  0: 'OVGR fault',
  1: 'RPR fault',
};

// AC charger alarm codes 1 (Appendix 8)
export const AC_CHARGER_ALARM_CODES1: Record<number, string> = {
  0: 'Grid overvoltage',
  1: 'Grid undervoltage',
  2: 'Overload',
  3: 'Short circuit',
  4: 'Charging output overcurrent',
  5: 'Leak current out of limit',
  6: 'Grounding fault',
  7: 'Abnormal phase sequence of grid wiring',
  8: 'PEN Fault',
};

// AC charger alarm codes 2 (Appendix 9)
export const AC_CHARGER_ALARM_CODES2: Record<number, string> = {
  0: 'Leak current detection circuit fault',
  1: 'Relay stuck',
  2: 'Pilot circuit fault',
  3: 'Auxiliary power supply module fault',
  4: 'Electric lock fault',
  5: 'Lamp panel communication fault',
};

// AC charger alarm codes 3 (Appendix 10)
export const AC_CHARGER_ALARM_CODES3: Record<number, string> = {
  0: 'Too high internal temperature',
  1: 'Charging cable fault',
  2: 'Meter communication fault',
};
